name: Site generation

on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 */2 * * 4"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Generate HTML
      run: python plotquisition/main.py
    - name: Commit newly generated HTML
      # You may pin to the exact commit or the version.
      uses: stefanzweifel/git-auto-commit-action@v4.7.2
      with:
        # Commit message
        commit_message: Generated index.html
        # File pattern used for `git add`. For example `src/\*.js`
        #file_pattern: index.html
    - run: date -r index.html '+$Y-%m-%d %H:%M'
    - run: LAST_BUILD="$(date -r index.html '+$Y-%m-%d %H:%M')" >> $GITHUB_ENV
    - run: echo $LAST_BUILD
    - name: Updating badge
      uses: Schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 8c97860b962cecec2f16ccf1b5a87554
        filename: last_build.json
        label: Updated
        message: ${{ env.LAST_BUILD }}
