name: Unit tests

on:
  push:
    branches:
      - main
      - unit-testing

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - uses: actions/cache@v2
      id: cache
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3-${{ hashFiles('**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip3-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
        pip show coverage
    - name: List pip cache
      run: ls ~/.cache/pip
    - name: Run tests
      run: ./test.sh
