name: Python package

on:
  push:
    branches:
      - main
      - unit-testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run tests
      run: test.sh
